# Generated by Django 3.2 on 2021-09-09 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_rename_user_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL, verbose_name='Studenci'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
    ]
